#3: create main single activity.
lusicom/SpaceX-Launch-Info-App pull request #7
Opened 2022-01-26 10:53 UTC by lusicom

2022-01-26 13:19 UTC, andreysergaev requested changes
Good job, please make a changes according to my request and also structure your files using packages.

2022-01-26 13:19 UTC, andreysergaev commented on app/src/main/java/com/example/spacex_launchinfoapp/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
please separate this method to different methods. This method is too long with a different purposes. 
You can do smth like this: 

```
override fun onCreate(savedInstanceState: Bundle?) {
       setContentView(R.layout.activity_main)
       setSupportActionBar(toolbar)
       initDrawer()
       initNavigation()
}
```

2022-01-26 16:47 UTC, lusicom commented on app/src/main/java/com/example/spacex_launchinfoapp/MainActivity.kt
> +        drawerLayout = findViewById(R.id.drawer_layout)
✅

2022-01-27 15:28 UTC, lusicom commented on app/src/main/java/com/example/spacex_launchinfoapp/MainActivity.kt
> +
✅

2022-01-30 08:58 UTC, shaygini approved these changes

2022-01-30 09:01 UTC, merged